/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("com.github.zhkl0228.java-conventions")
}

dependencies {
    api(libs.com.github.zhkl0228.unicorn)
    api(libs.com.github.zhkl0228.capstone)
    api(libs.com.github.zhkl0228.keystone)
    api(libs.commons.codec.commons.codec)
    api(libs.org.apache.commons.commons.collections4)
    api(libs.commons.io.commons.io)
    api(libs.commons.logging.commons.logging)
    api(libs.com.alibaba.fastjson)
    api(libs.com.github.zhkl0228.demumble)
}

description = "unidbg-api"

java {
    withJavadocJar()
}
