/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

pluginManagement {
    // Include 'plugins build' to define convention plugins.
    includeBuild("build-logic")
}

rootProject.name = "unidbg"
include(":unidbg-android")
include(":unidbg-api")
include(":unidbg-dynarmic")
include(":unidbg-hypervisor")
include(":unidbg-ios")
include(":unidbg-kvm")
include(":unidbg-unicorn2")
project(":unidbg-dynarmic").projectDir = file("backend/dynarmic")
project(":unidbg-hypervisor").projectDir = file("backend/hypervisor")
project(":unidbg-kvm").projectDir = file("backend/kvm")
project(":unidbg-unicorn2").projectDir = file("backend/unicorn2")
