/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("com.github.zhkl0228.java-conventions")
}

dependencies {
    api(project(":unidbg-api"))
    api(libs.net.dongliu.apk.parser)
    testImplementation(project(":unidbg-dynarmic"))
    testImplementation(project(":unidbg-hypervisor"))
    testImplementation(project(":unidbg-kvm"))
    testImplementation(project(":unidbg-unicorn2"))
}

description = "unidbg-android"

java {
    withJavadocJar()
}
